CREATE DATABASE ruhakweb
	CHARACTER SET utf8
	COLLATE utf8_hungarian_ci;

CREATE TABLE ruhakweb.poloadatok (
  id INT(11) NOT NULL AUTO_INCREMENT,
  meret VARCHAR(3) DEFAULT NULL,
  szín VARCHAR(10) DEFAULT NULL,
  marka VARCHAR(6) DEFAULT NULL,
  ar INT(11) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB;

CREATE TABLE ruhakweb.nadragok (
  id INT(11) NOT NULL AUTO_INCREMENT,
  meret VARCHAR(3) DEFAULT NULL,
  szín VARCHAR(10) DEFAULT NULL,
  marka VARCHAR(6) DEFAULT NULL,
  ar INT(11) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB;

CREATE TABLE ruhakweb.puloverek (
  id INT(11) NOT NULL AUTO_INCREMENT,
  meret VARCHAR(3) DEFAULT NULL,
  szín VARCHAR(10) DEFAULT NULL,
  marka VARCHAR(6) DEFAULT NULL,
  ar INT(11) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB;