--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.2.23.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2023.03.06. 9:04:42
-- Server version: 5.5.5-10.1.38-MariaDB
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

DROP DATABASE IF EXISTS ruhakweb;

CREATE DATABASE IF NOT EXISTS ruhakweb
	CHARACTER SET utf8
	COLLATE utf8_hungarian_ci;

--
-- Set default database
--
USE ruhakweb;

--
-- Create table `categories`
--
CREATE TABLE IF NOT EXISTS categories (
  id INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 3,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create table `products`
--
CREATE TABLE IF NOT EXISTS products (
  id INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(50) DEFAULT NULL,
  size VARCHAR(3) DEFAULT NULL,
  color VARCHAR(10) DEFAULT NULL,
  price DECIMAL(19, 2) DEFAULT NULL,
  quantity SMALLINT(6) DEFAULT NULL,
  categoryId INT(11) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 7,
AVG_ROW_LENGTH = 2730,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create foreign key
--
ALTER TABLE products 
  ADD CONSTRAINT FK_products_categories_id FOREIGN KEY (categoryId)
    REFERENCES categories(id);

--
-- Create table `users`
--
CREATE TABLE IF NOT EXISTS users (
  id INT(11) NOT NULL AUTO_INCREMENT,
  firstName VARCHAR(255) DEFAULT NULL,
  lastNamer VARCHAR(255) DEFAULT NULL,
  gender VARCHAR(255) DEFAULT NULL,
  userName VARCHAR(255) DEFAULT NULL,
  email VARCHAR(50) DEFAULT NULL,
  password VARCHAR(255) DEFAULT NULL,
  number INT(11) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 6,
AVG_ROW_LENGTH = 3276,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create table `baskets`
--
CREATE TABLE IF NOT EXISTS baskets (
  id INT(11) NOT NULL AUTO_INCREMENT,
  userId INT(11) DEFAULT NULL,
  productId INT(11) DEFAULT NULL,
  buyingId INT(11) DEFAULT NULL,
  quantity SMALLINT(6) DEFAULT NULL,
  date DATETIME DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create foreign key
--
ALTER TABLE baskets 
  ADD CONSTRAINT FK_baskets_products_id FOREIGN KEY (productId)
    REFERENCES products(id);

--
-- Create foreign key
--
ALTER TABLE baskets 
  ADD CONSTRAINT FK_baskets_users_id FOREIGN KEY (userId)
    REFERENCES users(id);

-- 
-- Dumping data for table categories
--
INSERT INTO categories VALUES
(1, 'Hoodie'),
(2, 'Pants');

-- 
-- Dumping data for table users
--
INSERT INTO users VALUES
(1, 'Nagy', 'József', 'Férfi', 'Nagyjozsi1212', 'nagyjozsef2000@gmail.com', 'adsjiajsdji213', 2147483647),
(2, 'Kiss', 'Csaba', 'Férfi', 'csabakiss12', 'kiss.csaba47@gmail.com', 'ajofghgjhgpojghj456', 2147483647),
(3, 'Szabó', 'Attila', 'Férfi', 'szaboattila98', 'attilaszabo887@gmail.com', 'uirtzrtziourtoi234', 2147483647),
(4, 'Erika', 'Zoltán', 'Nő', 'zoltanerika34', 'zoltanerika2000@gmail.com', 'iututizutoitzu67', 2147483647),
(5, 'Tóth', 'Lili', 'Nő', 'liltoth65', 'tothlili@gmail.com', 'mvbmnvmnvnv677', 2147483647);

-- 
-- Dumping data for table products
--
INSERT INTO products VALUES
(1, 'Nike Tech Fleece Pants', 'XS', 'Fekete', 38000.00, 30, 2),
(2, 'Nike Club Pants', 'S', 'Fekete', 18000.00, 50, 2),
(3, 'Nike Swoosh Pants', 'M', 'Fehér', 28000.00, 10, 2),
(4, 'Nike Sportswear Cargo Pants', 'L', 'Fekete', 25000.00, 25, 2),
(5, 'Nike Tech Fleece Hoodie', 'XS', 'Fekete', 45000.00, 28, 1),
(6, 'Nike Club Fleece Hoodie', 'S', 'Fehér', 21000.00, 23, 2);

-- 
-- Dumping data for table baskets
--
-- Table ruhakweb.baskets does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;